2021-09-24 13:15:20,225 - werkzeug - [INFO]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-09-24 13:15:30,749 - app - [INFO]: Init finished!
2021-09-24 13:15:30,752 - werkzeug - [INFO]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-09-24 16:37:37,194 - werkzeug - [INFO]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-09-24 16:59:06,513 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 16:59:06] "[31m[1mPOST /api/v1/media/upload_image HTTP/1.1[0m" 400 -
2021-09-24 16:59:22,069 - werkzeug - [INFO]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-09-24 16:59:27,998 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 16:59:27] "[31m[1mPOST /api/v1/media/upload_image HTTP/1.1[0m" 400 -
2021-09-24 17:00:20,036 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:00:20] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:00:26,567 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:00:26] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:00:27,475 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:00:27] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:01:55,963 - blueprints.search - [ERROR]: image search!
Traceback (most recent call last):
  File "D:\TJU\¥ÛÀƒ…œ\ µ—µ\shixun\blueprints\search.py", line 31, in image
    res = search(img_file.content, 1000)
AttributeError: 'BaseQuery' object has no attribute 'content'
2021-09-24 17:01:55,966 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:01:55] "GET /api/v1/search/image/20 HTTP/1.1" 200 -
2021-09-24 17:02:43,635 - werkzeug - [INFO]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-09-24 17:02:46,903 - blueprints.search - [ERROR]: image search!
Traceback (most recent call last):
  File "D:\TJU\¥ÛÀƒ…œ\ µ—µ\shixun\blueprints\search.py", line 31, in image
    res = search(img_file.content, 1000)
TypeError: search() takes 0 positional arguments but 2 were given
2021-09-24 17:02:46,971 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:02:46] "GET /api/v1/search/image/20 HTTP/1.1" 200 -
2021-09-24 17:03:33,299 - werkzeug - [INFO]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-09-24 17:03:33,508 - blueprints.search - [ERROR]: image search!
Traceback (most recent call last):
  File "c:\users\snowing\anaconda3\lib\site-packages\PIL\JpegImagePlugin.py", line 633, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\TJU\¥ÛÀƒ…œ\ µ—µ\shixun\blueprints\search.py", line 31, in image
    res = search_img(img_file.content, 1000)
  File "D:\TJU\¥ÛÀƒ…œ\ µ—µ\shixun\search_image.py", line 26, in search_img
    img.save(tmp)
  File "c:\users\snowing\anaconda3\lib\site-packages\PIL\Image.py", line 2172, in save
    save_handler(self, fp, filename)
  File "c:\users\snowing\anaconda3\lib\site-packages\PIL\JpegImagePlugin.py", line 635, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode RGBA as JPEG
2021-09-24 17:03:33,587 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:03:33] "GET /api/v1/search/image/20 HTTP/1.1" 200 -
2021-09-24 17:05:17,917 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:05:17] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:05:19,128 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:05:19] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:05:24,305 - blueprints.search - [ERROR]: image search!
Traceback (most recent call last):
  File "D:\TJU\¥ÛÀƒ…œ\ µ—µ\shixun\blueprints\search.py", line 31, in image
    res = search_img(img_file.content, 1000)
  File "D:\TJU\¥ÛÀƒ…œ\ µ—µ\shixun\search_image.py", line 45, in search_img
    h5f = h5py.File('feature/product.h5', 'r')
  File "c:\users\snowing\anaconda3\lib\site-packages\h5py\_hl\files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "c:\users\snowing\anaconda3\lib\site-packages\h5py\_hl\files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'feature/product.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2021-09-24 17:05:24,379 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:05:24] "GET /api/v1/search/image/23 HTTP/1.1" 200 -
2021-09-24 17:05:50,669 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:05:50] "GET /api/v1/search/image/23 HTTP/1.1" 200 -
2021-09-24 17:06:22,934 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:06:22] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:06:24,041 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:06:24] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:06:33,611 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:06:33] "GET /api/v1/search/image/23 HTTP/1.1" 200 -
2021-09-24 17:07:17,468 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:07:17] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:07:18,925 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:07:18] "POST /api/v1/media/upload_image HTTP/1.1" 200 -
2021-09-24 17:08:16,178 - blueprints.search - [ERROR]: image search!
Traceback (most recent call last):
  File "D:\TJU\¥ÛÀƒ…œ\ µ—µ\shixun\blueprints\search.py", line 31, in image
    res = search_img(img_file.content, 1000)
  File "D:\TJU\¥ÛÀƒ…œ\ µ—µ\shixun\search_image.py", line 45, in search_img
    h5f = h5py.File('feature/product.h5', 'r')
  File "c:\users\snowing\anaconda3\lib\site-packages\h5py\_hl\files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "c:\users\snowing\anaconda3\lib\site-packages\h5py\_hl\files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'feature/product.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2021-09-24 17:08:16,254 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:08:16] "GET /api/v1/search/image/23 HTTP/1.1" 200 -
2021-09-24 17:09:05,435 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:09:05] "POST /api/v1/user/login HTTP/1.1" 200 -
2021-09-24 17:10:42,427 - tensorflow - [WARNING]: 5 out of the last 9 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000025CB1E27B80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2021-09-24 17:10:43,101 - tensorflow - [WARNING]: 6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000025CB1E27F70> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2021-09-24 17:10:44,138 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:10:44] "POST /api/v1/product/add HTTP/1.1" 200 -
2021-09-24 17:10:48,780 - werkzeug - [INFO]: 127.0.0.1 - - [24/Sep/2021 17:10:48] "GET /api/v1/search/image/23 HTTP/1.1" 200 -
